### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Codfgb** [TheC0mpany/savedecrypter-by-ama6nen#1]
It's not working. It gives a meaningless output like "çäá¢çä±äœ"

**Comment by TheC0mpany** [comment]
Solve ur self

**Comment by Codfgb** [comment]
How can i solve it. I don't know how it works. LOL

**Comment by TheC0mpany** [comment]
I'm not program that, it's ama6nen project. I upload that only for educational purpose

**Comment by TheC0mpany** [comment]
Because original repo is deleted
